myList = [12]
myList.insert(0, 5)
myList.insert(1, 10)
myList.insert(0, 6)
print(myList)
myList.remove(6)
myList.append(9)
myList.append(1)
myList.sort()
print(myList)
myList.pop()
myList.reverse()
print(myList)